import json
from pathlib import Path
from typing import Optional
import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell

from dist_automl.working_dir.yaml_class import YamlConfig, YamlManager


class WorkingDirectory:
    BASE_FOLDERS = ("analysis", "utils", "pipeline")
    jupyter_file = "experiment.ipynb"

    def __init__(
        self,
        project_root: Path,
        config_path: Optional[Path] = None,
        exist_ok: bool = True,
    ):
        if not isinstance(project_root, Path):
            raise TypeError("project_root must be a pathlib.Path")

        project_root = project_root.expanduser().resolve()

        if not project_root.is_absolute():
            raise ValueError("project_root must be an absolute path")




        self._root = project_root
        self._root.mkdir(parents=True, exist_ok=exist_ok)

        self._ensure_base_structure()





        if config_path is None:
            config_path = self._root / "config.yaml"
        else:
            if not isinstance(config_path, Path):
                raise TypeError("config_path must be a pathlib.Path")

            if not config_path.is_absolute():
                config_path = self._root / config_path

            config_path = config_path.resolve()

        if config_path.suffix not in (".yaml", ".yml"):
            raise ValueError("Config file must have .yaml or .yml extension")

        self._config_path = config_path

        self._config = YamlConfig(self._config_path)

        self._manager = YamlManager(self._config)



    _GITIGNORE_ENTRIES = [
        "# Auto-generated by AutoML — safe to edit",
        "dashboard_runs/",
        "__pycache__/",
        "*.py[cod]",
        ".ipynb_checkpoints/",
        "config.yaml.lock",
    ]

    def _ensure_base_structure(self) -> None:
        for folder in self.BASE_FOLDERS:
            (self._root / folder).mkdir(parents=True, exist_ok=True)

        self._ensure_gitignore()

    def _ensure_gitignore(self) -> None:
        """Create or update .gitignore with essential ignore entries."""
        gi_path = self._root / ".gitignore"

        if gi_path.exists():
            existing = gi_path.read_text(encoding="utf-8")
            existing_lines = set(existing.splitlines())
            missing = [
                e for e in self._GITIGNORE_ENTRIES
                if e not in existing_lines and not e.startswith("#")
            ]
            if missing:
                suffix = "\n" if existing.endswith("\n") else "\n\n"
                gi_path.write_text(
                    existing + suffix + "\n".join(missing) + "\n",
                    encoding="utf-8",
                )
        else:
            gi_path.write_text(
                "\n".join(self._GITIGNORE_ENTRIES) + "\n",
                encoding="utf-8",
            )

    @property
    def root(self) -> Path:
        return self._root

    @property
    def config(self) -> YamlConfig:
        return self._config

    @property
    def manager(self) -> YamlManager:
        return self._manager
    
    
    
    
#--------------------------------------------------------------------------------



    def _validate_relative_path(self, path: Path, expected_root: str) -> Path:
        if not isinstance(path, Path):
            raise TypeError("path must be a pathlib.Path")

        path = path.expanduser()

        if path.is_absolute():
            try:
                relative_path = path.resolve().relative_to(self._root.resolve())
            except ValueError:
                raise ValueError("Absolute path must be inside project root")
        else:
            relative_path = path
            
        if ".." in relative_path.parts:
            raise ValueError("Path traversal outside project root is not allowed")

        if relative_path.suffix != ".py":
            raise ValueError("Only .py files are allowed")

        parts = relative_path.parts
        
        if not parts or parts[0] != expected_root:
            raise ValueError(f"Path must start with '{expected_root}/'")

        return relative_path
    
    
    def _absolute(self, relative_path: Path) -> Path:
        return (self._root / relative_path).resolve()

    def _create_file_if_needed(
        self,
        relative_path: Path,
        content: str = "",
        overwrite: bool = True,
    ) -> None:
        abs_path = self._absolute(relative_path)

        abs_path.parent.mkdir(parents=True, exist_ok=True)

        if abs_path.exists() and not overwrite:
            return

        abs_path.write_text(content, encoding="utf-8")


    def _delete_file_if_exists(self, relative_path: Path) -> None:
        abs_path = self._absolute(relative_path)
        if abs_path.exists():
            abs_path.unlink()
            
#-----------------------------------------------------------------


    def list_notebooks(self) -> list[dict]:
        """Return a list of all .ipynb files under the project root (relative paths)."""
        notebooks = []
        for nb_path in self._root.rglob("*.ipynb"):
            # Skip checkpoint directories
            if ".ipynb_checkpoints" in nb_path.parts:
                continue
            relative = nb_path.relative_to(self._root)
            notebooks.append({
                "name": nb_path.stem,
                "path": relative.as_posix(),
            })
        return notebooks

    def manage_notebook_cell(
        self,
        action: str,
        notebook: str = None,
        index: int = None,
        content: str = None,
        cell_type: str = "code",
    ):
        """
        Manage cells in a Jupyter notebook inside the project.

        Args:
            action: 'read', 'add', 'edit', or 'delete'
            notebook: Path to the .ipynb file relative to the project root.
                      Defaults to 'experiment.ipynb' when None.
            index: Cell index for targeted operations.
            content: Cell content for 'add' / 'edit'.
            cell_type: 'code' or 'markdown' (used by 'add').
        """
        notebook_rel = notebook or self.jupyter_file
        file_path = (self._root / notebook_rel).resolve()

        # Safety: must stay inside project root
        try:
            file_path.relative_to(self._root)
        except ValueError:
            return f"Error: Notebook path must be inside the project root."

        if file_path.suffix != ".ipynb":
            return "Error: File must have a .ipynb extension."

        display_name = Path(notebook_rel).as_posix()

        # Load or initialize the notebook
        if file_path.exists():
            with file_path.open('r', encoding='utf-8') as f:
                nb = nbformat.read(f, as_version=4)
        elif action == 'add':
            file_path.parent.mkdir(parents=True, exist_ok=True)
            nb = nbformat.v4.new_notebook()
        else:
            return f"Error: Notebook '{display_name}' not found in project."

        # Perform the requested action
        if action == 'read':
            if index is not None:
                if 0 <= index < len(nb.cells):
                    return {"notebook": display_name, "index": index, "cell": nb.cells[index]}
                return "Error: Invalid index."
            return {
                "notebook": display_name,
                "cells": [{"index": i, "type": c.cell_type, "source": c.source} for i, c in enumerate(nb.cells)],
            }

        elif action == 'add':
            new_cell = new_code_cell(content or "") if cell_type == "code" else new_markdown_cell(content or "")
            if index is not None:
                nb.cells.insert(index, new_cell)
            else:
                nb.cells.append(new_cell)

        elif action == 'edit':
            if index is not None and 0 <= index < len(nb.cells):
                nb.cells[index].source = content if content is not None else nb.cells[index].source
            else:
                return "Error: Invalid index."

        elif action == 'delete':
            if index is not None and 0 <= index < len(nb.cells):
                nb.cells.pop(index)
            else:
                return "Error: Invalid index."

        # Save and return status
        with file_path.open('w', encoding='utf-8') as f:
            nbformat.write(nb, f)
        return f"Success: {action} operation completed on '{display_name}'."


    def update_utils(
        self,
        name: str,
        path: Path,
        metadata: Optional[dict] = None,
        content: str = "",
        overwrite: bool = True,
    ) -> None:
        relative_path = self._validate_relative_path(path, "utils")

        try:
            with self._manager:
                self._create_file_if_needed(
                    relative_path,
                    content=content,
                    overwrite=overwrite,
                )

                self._manager.update_utils(
                    name=name,
                    path=relative_path,
                    metadata=metadata,
                )

        except Exception:
            self._delete_file_if_exists(relative_path)
            raise
            
            
            
    def delete_utils(self, name: str) -> None:
        entry = self._config.get(f"utils.files.{name}")
        if not entry:
            raise KeyError(f"Utils entry '{name}' not found")

        relative_path = Path(entry["path"])

        with self._manager:
            self._manager.delete_utils(name)
            self._delete_file_if_exists(relative_path)
            
            
#--------------------------------------------------------------------


    def update_analysis(
        self,
        name: str,
        path: Path,
        output_type: Optional[str] = None,
        metadata: Optional[dict] = None,
        content: str = "",
        overwrite: bool = True,
    ) -> None:
        relative_path = self._validate_relative_path(path, "analysis")

        try:
            with self._manager:
                self._create_file_if_needed(
                    relative_path,
                    content=content,
                    overwrite=overwrite,
                )

                self._manager.update_analysis(
                    name=name,
                    path=relative_path,
                    output_type=output_type,
                    metadata=metadata,
                )

        except Exception:
            self._delete_file_if_exists(relative_path)
            raise
            
            
    def delete_analysis(self, name: str) -> None:
        entry = self._config.get(f"analysis.files.{name}")
        if not entry:
            raise KeyError(f"Analysis entry '{name}' not found")

        relative_path = Path(entry["path"])

        # Clean up dashboard artifacts created from this analysis script
        self._cleanup_dashboard_artifacts(relative_path)

        with self._manager:
            self._manager.delete_analysis(name)
            self._delete_file_if_exists(relative_path)

    def _cleanup_dashboard_artifacts(self, relative_script_path: Path) -> None:
        """Remove dashboard data/images and metadata.json entry for a given analysis script."""
        dashboard_dir = self._root / "dashboard_runs"
        meta_file = dashboard_dir / "metadata.json"

        if not meta_file.exists():
            return

        try:
            metadata = json.loads(meta_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return

        scripts = metadata.get("scripts", {})

        # The capture module uses str(absolute_script_path) as the key
        abs_script_path = str(self._absolute(relative_script_path))

        if abs_script_path not in scripts:
            return

        # Delete each referenced data/image file
        for var_name, var_info in scripts[abs_script_path].items():
            artifact_path = var_info.get("path")
            if artifact_path:
                full_path = dashboard_dir / artifact_path
                if full_path.exists():
                    full_path.unlink()

        # Remove the script entry from metadata
        del scripts[abs_script_path]
        meta_file.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
            
            
#----------------------------------------------------------------

    def update_pipeline_element(
        self,
        stage: str,
        name: str,
        path: Path,
        metadata: Optional[dict] = None,
        depends_on: Optional[list[str]] = None,
        content: str = "",
        overwrite: bool = True,
    ) -> None:
        

        relative_path = self._validate_relative_path(path, "pipeline")

        try:
            with self._manager:
                self._create_file_if_needed(
                    relative_path,
                    content=content,
                    overwrite=overwrite,
                )

                self._manager.update_pipeline(
                    stage=stage,
                    name=name,
                    path=relative_path,
                    metadata=metadata,
                    depends_on=depends_on,
                )

        except Exception:
            self._delete_file_if_exists(relative_path)
            raise
            
    def delete_pipeline_element(self, stage: str, name: str) -> None:

        entry = self._config.get(f"pipeline.stages.{stage}.elements.{name}")
        if not entry:
            raise KeyError(f"Pipeline element '{stage}.{name}' not found")

        relative_path = Path(entry["path"])

        with self._manager:
            self._manager.delete_element(stage, name)
            self._delete_file_if_exists(relative_path)

    def update_dataset(
        self,
        name: str,
        source: str,
        dtype: Optional[str] = None,
        description: Optional[str] = None,
        metadata: Optional[dict] = None,
    ) -> None:
        with self._manager:
            self._manager.update_dataset(
                name=name,
                source=source,
                dtype=dtype,
                description=description,
                metadata=metadata,
            )

    def delete_dataset(self, name: str) -> None:
        with self._manager:
            self._manager.delete_dataset(name)

    def update_metadata(self, updates: dict) -> None:
        """Set or update top-level project metadata key-value pairs."""
        with self._manager:
            self._manager.update_metadata(updates)

    def delete_metadata(self, key: str) -> None:
        """Delete a single key from project metadata."""
        with self._manager:
            self._manager.delete_metadata(key)

    def get_metadata(self, key: str = None):
        """Get all project metadata or a specific key."""
        return self._manager.get_metadata(key)

    def write_ops_file(
        self,
        file_path: str,
        content: str,
        name: str = None,
        description: str = None,
        metadata: Optional[dict] = None,
        track: bool = False,
    ) -> str:
        """Create or overwrite an ops/management file and optionally track it in config."""
        rel_path = Path(file_path)
        abs_path = (self._root / rel_path).resolve()

        # Safety check
        try:
            abs_path.relative_to(self._root)
        except ValueError:
            raise ValueError("File path must be inside the project root.")

        abs_path.parent.mkdir(parents=True, exist_ok=True)
        abs_path.write_text(content, encoding="utf-8")

        if track:
            ops_name = name or rel_path.stem
            with self._manager:
                self._manager.update_ops(
                    name=ops_name,
                    path=rel_path,
                    description=description,
                    metadata=metadata,
                )

        return rel_path.as_posix()

    def append_ops_file(self, file_path: str, content: str) -> None:
        """Append content to an existing ops/management file."""
        abs_path = (self._root / file_path).resolve()

        try:
            abs_path.relative_to(self._root)
        except ValueError:
            raise ValueError("File path must be inside the project root.")

        if not abs_path.exists():
            raise FileNotFoundError(f"File '{file_path}' does not exist. Use 'write' to create it first.")

        existing = abs_path.read_text(encoding="utf-8")
        separator = "\n\n" if existing and not existing.endswith("\n") else ("\n" if existing else "")
        abs_path.write_text(existing + separator + content, encoding="utf-8")

    def read_ops_file(self, file_path: str) -> str:
        """Read an ops/management file."""
        abs_path = (self._root / file_path).resolve()

        try:
            abs_path.relative_to(self._root)
        except ValueError:
            raise ValueError("File path must be inside the project root.")

        if not abs_path.exists():
            raise FileNotFoundError(f"File '{file_path}' does not exist.")

        return abs_path.read_text(encoding="utf-8")

    def update_ops_tracking(
        self,
        name: str,
        path: str,
        description: str = None,
        metadata: Optional[dict] = None,
    ) -> None:
        """Register an ops file in config without writing content."""
        with self._manager:
            self._manager.update_ops(
                name=name,
                path=Path(path),
                description=description,
                metadata=metadata,
            )

    def delete_ops(self, name: str) -> None:
        """Remove an ops file entry from config."""
        with self._manager:
            self._manager.delete_ops(name)

    def get_ops(self, name: str = None):
        """Get all tracked ops files or a specific one."""
        return self._manager.get_ops(name)

    def check_sync(self) -> list[str]:
        return self._manager.check_project_sync(self._root)
    
    
    
if __name__ == "__main__":
    test_path = Path(__file__).parent.parent.parent.parent.absolute() / "wd_test"
    
    Dir = WorkingDirectory(test_path)
    
    Dir.check_sync()
    Dir.update_utils("helper",Path("utils/helper.py"),content="works")
    Dir.update_analysis("bar graph",Path("analysis/barg.py"),"graph",content="worksss")
    Dir.update_pipeline_element("prepro_2","colmix",Path("pipeline/ok.py"),content="work")
    Dir.check_sync()
    _ = input()
    Dir.delete_utils("helper")
    Dir.delete_analysis("bar graph")
    Dir.delete_pipeline_element(stage="prepro",name="colmix")
    # Dir.delete_pipeline_element(stage="prepro")
    Dir.check_sync()
    
    